<a href="https://colab.research.google.com/github/MinThuKhant763/machine-learning/blob/main/Linear_Regression_Using_Multiple_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
X = np.array([[1000,2],[1500,3],[1800,3],[2400,4],[3000,4]])
Y = np.array([180000,250000,270000,320000,360000])
print(X)
print(Y)

[[1000    2]
 [1500    3]
 [1800    3]
 [2400    4]
 [3000    4]]
[180000 250000 270000 320000 360000]


In [3]:
X_b = np.c_[np.ones((X.shape[0],1)),X]
print(X_b)

[[1.0e+00 1.0e+03 2.0e+00]
 [1.0e+00 1.5e+03 3.0e+00]
 [1.0e+00 1.8e+03 3.0e+00]
 [1.0e+00 2.4e+03 4.0e+00]
 [1.0e+00 3.0e+03 4.0e+00]]


In [4]:
weights = np.linalg.inv(X_b.T@X_b)@X_b.T@Y
print(weights)

[6.82849604e+04 5.54089710e+01 3.13192612e+04]


In [5]:
alpha = weights[0]
beta_area = weights[1]
beta_room = weights[2]
print("Intercept (alpha)",round(alpha,2))
print("Coefficient for Area",round(beta_area,2))
print("Coefficient for Room", round(beta_room,2))



Intercept (alpha) 68284.96
Coefficient for Area 55.41
Coefficient for Room 31319.26


In [6]:
Y_pred = X_b@weights
print(Y_pred)

[186332.45382586 245356.20052771 261978.89182058 326543.53562005
 359788.91820581]


In [7]:
for actual, predicited in zip(Y,Y_pred):
  print("Actual ",round(actual,2),"Predicted",round(predicited,2))


Actual  180000 Predicted 186332.45
Actual  250000 Predicted 245356.2
Actual  270000 Predicted 261978.89
Actual  320000 Predicted 326543.54
Actual  360000 Predicted 359788.92


In [8]:
new_house = np.array([1,2200,3])
predicted_price = new_house@weights
print("Predicted Price for 2200sq ft and 3 rooms",round(predicted_price))

Predicted Price for 2200sq ft and 3 rooms 284142


In [9]:
SS_res = np.sum((Y-Y_pred)**2)
SS_total = np.sum((Y-np.mean(Y))**2)
r2 = 1 - (SS_res/SS_total)
print("R2 scores ",round(r2,2))

R2 scores  0.99
