<a href="https://colab.research.google.com/github/MinThuKhant763/machine-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

1

In [ ]:
a.size

5

In [ ]:
x1 = np.array([4,0,3])
y1 = np.array([2,5,6])
result = x1*y1
print(result)

[ 8  0 18]


List Vs Numpy Array

In [ ]:
l = list([1,2,3,4])
l2 = np.array([1,2,3])
print(l)
print(l2)

[1, 2, 3, 4]
[1 2 3]


Python List

In [ ]:
l.append(5)
l

[1, 2, 3, 4, 5]

In [ ]:
l = l+[5]
l

[1, 2, 3, 4, 5, 5]

Numpy Arrary

In [ ]:
l2 = np.append(l2,[4,5])
l2

array([1, 2, 3, 4, 5])

In [ ]:
l2 = l2 + np.array(2)
l2

array([3, 4, 5, 6, 7])

Mutiply

In [ ]:
#Python List
result1 = l * 3
print(result1)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
#Numpy Array
result2 = l2 * 3
print(result2)

[ 9 18 27]


dot product

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
dot_result = np.dot(a,b)
print(dot_result)

11


In [ ]:
dot_result1 = a@b
print(dot_result)

11


Transport

In [ ]:
num = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
num.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])